### ISSUE TITLE
Ey yo Roi D 🅱️oi wassup

### ISSUE THREAD

**Issue by Campiotti** [royAmmerschuber/WebVideoPlace#1]
🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️ 🅱️

**Comment by royAmmerschuber** [comment]
the problem is fixed
